twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # Add global variables that can be use over all templates 
    globals:
        website_name: 'African Learners' #African Learners Sama school
        website_slogan: 'Be, Learn, Connect'
        website_short_name: 'ALearners' #ALearners Sama school
        website_contact_help: 'contact@a-learners.com' #alearners.org Sama school
        website_contact_phone: '+221338257002'

when@test:
    twig:
        strict_variables: true
