vich_uploader:
    db_driver: orm

    mappings:
        course_image:
            uri_prefix: /course_images
            upload_destination: '%kernel.project_dir%/public/course_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_file:
            uri_prefix: /course_files
            upload_destination: '%kernel.project_dir%/public/course_files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
