vich_uploader:
    db_driver: orm

    mappings:
        course_image:
            uri_prefix: '%app.image_uploads_path%'
            upload_destination: '%kernel.project_dir%/public%app.image_uploads_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_file:
            uri_prefix: '%app.file_uploads_path%'
            upload_destination: '%kernel.project_dir%/public%app.file_uploads_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
