version: '3.3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# version: '3'

# services:
# ###> symfony/mailer ###
#   mailer:
#     image: schickling/mailcatcher
#     ports: [1025, 1080]
# ###< symfony/mailer ###

# ###> doctrine/doctrine-bundle ###
#   database:
#     ports:
#       - "5432"
# ###< doctrine/doctrine-bundle ###
